### ISSUE TITLE
Quick question about polarizeVCFbyOutgroup

### ISSUE THREAD

**Issue by jaholliday** [kullrich/bio-scripts#1]
I just found this script and was able to run it on my VCF. I wasn't clear if it's just adding the AA tag or switching genotype coding in the output when the original reference/alternate does not match ancestral/derived based on the outgroup. That is, if the original VCF has

Chr01	2667	.	T	C

Where 'T' is ref and 'C' is alt, and the outgroup is C/C, will the output be coded as 

Chr01	2667	.	C	T

And all the genotypes flipped accordingly?

Thanks!

**Comment by kullrich** [comment]
Hi,

the REF and ALT should be switched accordingly, like the GT fileds for the samples.

As you can see from the example it also switches the heterozygous samples.

e.g. the test.vcf file:
```
chr1    3000762 .       T       C       4824.78 PASS    AF=0.5;CM=0.000587;AN=170;AC=8  GT      1|1     0|0     0|0     1|1     1|1     1|0     0|1
chr1    3000770 .       C       T       934.37  PASS    AF=0.5;CM=0.000595;AN=170;AC=8  GT      0|0     0|0     0|0     1|1     1|1     1|0     0|1
chr1    3000772 .       T       C       4824.78 PASS    AF=0.5;CM=0.000587;AN=170;AC=8  GT      1/1     0/0     0/0     1/1     1/1     1/0     0/1
chr1    3000780 .       C       T       934.37  PASS    AF=0.5;CM=0.000595;AN=170;AC=8  GT      0/0     0/0     0/0     1/1     1/1     1/0     0/1
```

becomes (using sample 1 as the outgroup):

```
python polarizeVCFbyOutgroup.py -vcf test.vcf -out test.out -ind 1 -add
```

```
Namespace(add=True, ind=1, keep=False, out='test.out', vcf='test.vcf')
Parsed 4 sites.
Removed 0 sites due to missing allele info in switch individual.
Removed 0 sites with undefined ancestral state.
Switched REF and ALT allele for 2 sites.
```
 the test.out:

```
chr1    3000762 .       C       T       4824.78 PASS    AA=C;AF=0.5;CM=0.000587;AN=170;AC=8     GT      0|0     1|1     1|1     0|0     0|0     0|1     1|0
chr1    3000770 .       C       T       934.37  PASS    AA=C;AF=0.5;CM=0.000595;AN=170;AC=8     GT      0|0     0|0     0|0     1|1     1|1     1|0     0|1
chr1    3000772 .       C       T       4824.78 PASS    AA=C;AF=0.5;CM=0.000587;AN=170;AC=8     GT      0/0     1/1     1/1     0/0     0/0     0/1     1/0
chr1    3000780 .       C       T       934.37  PASS    AA=C;AF=0.5;CM=0.000595;AN=170;AC=8     GT      0/0     0/0     0/0     1/1     1/1     1/0     0/1
```

Best regards

Kristian

**Comment by jaholliday** [comment]
Thanks Kristian! This is what I thought but wanted to check. It's just what I needed and have not found elsewhere, which is surprising as it's a fundamental step in a lot of pop gen analyses. 

Cheers
Jason

**Comment by kullrich** [comment]
Hi @jaholliday,
yes you are right.
You will find in a lot of popgen software manuals that the VCF file to use should be polarized to the ancestral state but in a lot of publications I doubt it was done and just kept to be the original reference allele all sequences have been mapped to.
I hope the script will be useful for you.
Best regards
Kristian
